export const teamGroup = [
  {
    id: '1',
    name: 'Aksonov Yevhen',
    photo: './teamsphoto/aksonov.svg',
    link: 'https://www.linkedin.com/in/kotiko/',
    role: 'teamlead',
  },
  {
    id: '2',
    name: 'Viktoriia Sukhara',
    photo: './teamsphoto/sukhra.svg',
    link: 'https://www.linkedin.com/in/viktoriia-sukhara-31616a288/',
    role: 'scram master',
  },
  {
    id: '3',
    name: 'Oleksandr Sharyak',
    photo: '',
    link: 'https://www.linkedin.com/in/oleksandr-sharyak-b72a47289/',
    role: 'developer',
  },
  {
    id: '4',
    name: 'Konstantin Shkarupa',
    photo: './teamsphoto/shkarupa.svg',
    link: 'https://www.linkedin.com/in/konstantin-shkarupa/',
    role: 'developer',
  },
  {
    id: '5',
    name: 'Kate Zaharova',
    photo: './teamsphoto/zaharova.svg',
    link: 'https://www.linkedin.com/in/kate-zaharova',
    role: 'developer',
  },
  {
    id: '6',
    name: 'Anastasiia Parkhomenko',
    photo: '',
    link: 'https://www.linkedin.com/in/anastasiia-parkhomenko-dev/',
    role: 'developer',
  },
  {
    id: '7',
    name: 'Igor Volk',
    photo: '',
    link: 'https://www.linkedin.com/in/igor-volk',
    role: 'developer',
  },
];
