export const Month = [
  {
    date: '1, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '2, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '3, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '4, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '5, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '6, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '7, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '8, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '9, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '10, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '11, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '12, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '13, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '14, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '15, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '16, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '17, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '18, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '19, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '20, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '21, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '22, December',
    norma: '1.5 L',
    procent: '40%',
    servings: 2,
  },
  {
    date: '23, December',
    norma: '1.5 L',
    procent: '130%',
    servings: 5,
  },
  {
    date: '24, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '25, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '26, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '27, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '28, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '29, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '30, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
  {
    date: '31, December',
    norma: '2.0 L',
    procent: '0%',
    servings: 0,
  },
];
